backend:
  name: github
  repo: kebim/learn-site
  branch: main
  base_url: https://learnkebim.mibekebim.workers.dev
  auth_endpoint: /auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "lessons"
    label: "Teaching Materials"
    folder: "lessons"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Subject/Topic", name: "topic", widget: "string" }
      - { label: "Lesson Body", name: "body", widget: "markdown" }
